name: Markdown CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  markdown-link-check:
    name: Validation with markdown-link-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name:
      uses: gaurav-nelson/github-action-markdown-link-check@v1
